# Optional Postgres profile: ./gradlew bootRun --args='--spring.profiles.active=postgres'
spring.datasource.url=jdbc:postgresql://localhost:5432/rickdb
spring.datasource.username=rick
spring.datasource.password=rickrick
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
